change-id = 125535

[llvm]
download-ci-llvm = true

[build]
host = [ "${HOST}" ]
target = [
    "${HOST}",
    "wasm32-unknown-unknown",
    "wasm64-unknown-unknown"
]
docs = false
extended = true

[rust]
channel = "nightly"
description = "Dusk Network's Smart Contract Compiler"

lld = true

[dist]
compression-formats = ["gz"]
compression-profile = "best"
